steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-f",
        "packages/api/Dockerfile",
        "-t",
        "gcr.io/$PROJECT_ID/beam-api:$COMMIT_SHA",
        "-t",
        "gcr.io/$PROJECT_ID/beam-api:latest",
        ".",
      ]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/beam-api:$COMMIT_SHA"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/beam-api:latest"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    secretEnv:
      [
        "GITHUB_CLIENT_ID",
        "GITHUB_CLIENT_SECRET",
        "GITHUB_REDIRECT_URI",
        "JWT_SECRET",
      ]
    args:
      [
        "run",
        "deploy",
        "beam-api",
        "--image",
        "gcr.io/$PROJECT_ID/beam-api:$COMMIT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--allow-unauthenticated",
        "--port",
        "3001",
        "--memory",
        "512Mi",
        "--cpu",
        "1",
        "--min-instances",
        "0",
        "--max-instances",
        "10",
        "--set-env-vars",
        "NODE_ENV=production,GITHUB_CLIENT_ID=$$GITHUB_CLIENT_ID,GITHUB_CLIENT_SECRET=$$GITHUB_CLIENT_SECRET,GITHUB_REDIRECT_URI=$$GITHUB_REDIRECT_URI,JWT_SECRET=$$JWT_SECRET",
      ]

  # Ensure unauthenticated access is allowed
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "services",
        "add-iam-policy-binding",
        "beam-api",
        "--region=us-central1",
        "--member=allUsers",
        "--role=roles/run.invoker",
      ]

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/GITHUB_CLIENT_ID/versions/latest
      env: "GITHUB_CLIENT_ID"
    - versionName: projects/$PROJECT_ID/secrets/GITHUB_CLIENT_SECRET/versions/1
      env: "GITHUB_CLIENT_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/GITHUB_REDIRECT_URI/versions/latest
      env: "GITHUB_REDIRECT_URI"
    - versionName: projects/$PROJECT_ID/secrets/JWT_SECRET/versions/1
      env: "JWT_SECRET"

images:
  - "gcr.io/$PROJECT_ID/beam-api:$COMMIT_SHA"
  - "gcr.io/$PROJECT_ID/beam-api:latest"

options:
  logging: CLOUD_LOGGING_ONLY
